### ISSUE TITLE
Change default branch to master

### ISSUE THREAD

**Issue by caseyli** [AmaniLouendriz/PontsDeConnaisssance#2]
Hey @AmaniLouendriz, so it looks like the branch that you're doing your work on from your computer is `master`. While there are other ways to solve this, probably the easiest thing to do now is to change your default branch on GitHub.

The default branch is what shows up when you first load the page and also the first branch that Pull Requests are created from.

So here's what I would do

- In this repository on GitHub, click on the "Settings" tab
- Click on "Branches"
- Under "Default Branch", right now it probably says `main`. Click on the double-arrows to the right of it (do NOT click on the pencil)
- From the drop-down, choose `master` and click Update

There you go - now when you go to this repository, it'll default show the `master` branch.

**Comment by AmaniLouendriz** [comment]
Hello @caseyli @7chris71000  ,I did the thing with the branch, but the readme file (I have now a readme in 2 branches) is still on the other branch"main"; then I should just delete it (readme) and it's fine?

**Comment by chrisfrancis7** [comment]
@AmaniLouendriz you can either just delete it, or you can commit it on the `master` branch. 

`git checkout master`
Change the README.md to whatever you want. If you want what is on `main` just copy/paste from main.
`git add .`
`git commit -m "Updated README"`
`git push -u origin master`

Normally you dont push straight to `master` but for now you can since you aren't creating pull requests.

**Comment by AmaniLouendriz** [comment]
@7chris71000 Ok! Thanks!!
